name = "WHAD hugo theme"
license = "MIT"
licenselink = "https://github.com/whad-team/hugo-theme/blob/main/LICENSE"
description = "Minimal WHAD team derived from INSA Lab's minimal theme for hugo"
homepage = "https://github.com/whad-team/hugo-theme/"
demosite = ""
tags = ["minimal", "dark", "blog", "sass", "multilingual"]
features = ["blog", "sass", "dark", "multilingual"]
min_version = "0.114.0"

[author]
name = "Romain Cayre"
homepage = "https://insa-toulouse.fr"
